version: '3.7'
services:
    datascience-notebook:
        image: meesh-jupyter 
        volumes:
            - ./:/home/jovyan
        environment:
            GRANT_SUDO: "yes"
        user: root
        ports:
            - 8888:8888
        container_name: jupyter_notebook
        restart: always
